### ISSUE TITLE
Steve's UV undersides are inconsisent between models

### ISSUE THREAD

**Issue by Graxornam** [jam1garner/smash-minecraft-skins#11]
As part of some unknowable, source-accuracy reason or something, Steve (assuming all variants+Zombie, excluding Alex/Enderman) have the bottom UV of their heads flipped vertically.
My pointers tell me that along with basing their default Steve on the pre-shaven version, they retained the UV behavior as before the following update:
![image](https://user-images.githubusercontent.com/45780976/96335242-546ab800-1045-11eb-9487-4659223aec39.png)
This quirk does not apply to Alex's skin, and I'm uncertain regarding Enderman's (which is unique as-is).
Along with the underside of the head, _I'd assume & check for the same situation for all other under-side faces._

The 2 leftmost are the same texture, 2:1 format,
Middle is as viewed in the Minecraft Launcher.
Rightmost is a 1:1 edit of the same skin applied to the Alex model.
![image](https://user-images.githubusercontent.com/45780976/96335209-1a011b00-1045-11eb-86bb-12d1018a6b01.png)
And these are the skins used in the above screenshots:
![image](https://user-images.githubusercontent.com/45780976/96335430-829cc780-1046-11eb-9c9a-a50ccc20b45a.png)
![image](https://user-images.githubusercontent.com/45780976/96335428-80d30400-1046-11eb-84d5-2c002a5e37df.png)

**Comment by jam1garner** [comment]
Fixed in 1.1.0
