### ISSUE TITLE
Whenever the file is in my switch, smash bros comes up with an error saying "The software could not be started due to an error."

### ISSUE THREAD

**Issue by MasonPYT** [jam1garner/smash-minecraft-skins#12]
![IMG-20190315-WA0003](https://user-images.githubusercontent.com/73023351/96336556-9e20c600-1078-11eb-8241-4717374c2947.jpg)

An image like this one found on google is the only thing that shows up when I start smash and I dont know what it is, any fixes?

**Comment by jam1garner** [comment]
Try:

* Reinstalling atmosphere
* Checking for game corruption from the SD storage menu in system settings

This problem is not likely caused by my plugin, as this error message means my plugin couldn't have even started up yet.
