### ISSUE TITLE
Weird skin textures 

### ISSUE THREAD

**Issue by PrincessYoshi** [jam1garner/smash-minecraft-skins#14]
I would for example put Notch but it would appear all glitched and weird looking like this
![NotchFront](https://user-images.githubusercontent.com/72232609/96357636-6c792080-10b3-11eb-98f5-6f93e7495971.jpg)
![NotchBack](https://user-images.githubusercontent.com/72232609/96357638-6e42e400-10b3-11eb-8844-a9b8dad6033e.jpg)

**Comment by darkwinger344** [comment]
I also had this same issue. I was able to fix it by installing a previous version of ARCropolis (v0.9.0).

**Comment by jam1garner** [comment]
> I also had this issue. I was able to fix it by installing a previous version of ARCropolis (v0.9.0).

In that case, I'll close the issue as an arcropolis problem. Will reopen if evidence arises of the contrary.

**Comment by jam1garner** [comment]
Download arcropolis 0.9.2 this should be fixed.
