### ISSUE TITLE
Skin+UI not loading properly

### ISSUE THREAD

**Issue by Manito418** [jam1garner/smash-minecraft-skins#17]
Used the Java username feature to steal my skin and it puts my pants texture on the back of my arms + doesn't properly generate the UI.  My Minecraft username is "Manito"  , maybe you can see if you get the same results? Here's the skin it generated:

![Manito](https://user-images.githubusercontent.com/9992382/96541467-ebf22580-1254-11eb-91d2-bb99f34fdb84.png)

Update: As I was typing this, I solved my own problem, the skin was in 64x32 format. So I gave it an update to 64x64 and it loads correctly for the skin now and pretty much correctly for the UI.
Before:
![2020101921372300-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/9992382/96541847-bac62500-1255-11eb-93c1-aca43e809958.jpg)

After:
![2020101921494500-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/9992382/96541876-c580ba00-1255-11eb-81f1-e0de5fdc555b.jpg)

Up close of the skin:
![2020101921585500-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/9992382/96542148-53f53b80-1256-11eb-878d-b2cf2e13326e.jpg)

**Comment by jam1garner** [comment]
Probably fixed in #18. Gonna have someone test and will merge and push a patch fix if it works.

If you're eager to try it yourself, here's a download: https://cdn.discordapp.com/attachments/765686529292107777/767977215199412234/libminecraft_skins.nro
