### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by PlayfulWaffle12** [jam1garner/smash-minecraft-skins#21]
i was wondering if it would be possible so that when you use a skin on it, it creates a separate mod for it in the files? (could be an option or something) This would be really useful because if you want to play without the hassle of reselecting your skin all the time, or if somebody wanted to release a mod on gamebananna or something with ease

**Comment by jam1garner** [comment]
I explicitly don't want to support using this to export as a mod for gamebanana. I see no point to post low effort mods there when they could just use the PNG with this mod.

**Comment by PlayfulWaffle12** [comment]
what png?

**Comment by PlayfulWaffle12** [comment]
what about the renders?

**Comment by jam1garner** [comment]
no. if anything, wait and see if SMG makes their render library open source. if they do, it already has a skin -> render CLI built-in.
