### ISSUE TITLE
Error installing the mod

### ISSUE THREAD

**Issue by Staichi54** [jam1garner/smash-minecraft-skins#27]
![20201027_094015](https://user-images.githubusercontent.com/73539099/97317524-e12d2700-1838-11eb-814f-08e513c00636.jpg)

When im going to install the mod, this is whats apear , i have the last version of atmosphere, smash and the UMM
Pd: i dont know how to open the menu in the game for change the skin :b (i dont speack english, so i dont know if im writting this good)

**Comment by Craftyawesome** [comment]
Follow https://gamebanana.com/tuts/13505

**Comment by Staichi54** [comment]
> Follow https://gamebanana.com/tuts/13505

Say "ARCropolis config file not detected! Please run smash ultimate with ARCropolis set up!" I already opened the game, but it keeps sending me that message

**Comment by Craftyawesome** [comment]
> > Follow https://gamebanana.com/tuts/13505
> 
> Say "ARCropolis config file not detected! Please run smash ultimate with ARCropolis set up!" I already opened the game, but it keeps sending me that message
Does ARCropolis Ver. 0.9.3 show up on the title screen?

**Comment by Staichi54** [comment]
> > > Follow https://gamebanana.com/tuts/13505
> > 
> > 
> > Say "ARCropolis config file not detected! Please run smash ultimate with ARCropolis set up!" I already opened the game, but it keeps sending me that message
> > Does ARCropolis Ver. 0.9.3 show up on the title screen?

No ._. , just start normally smash

**Comment by Craftyawesome** [comment]
> > > > Follow https://gamebanana.com/tuts/13505
> > > 
> > > 
> > > Say "ARCropolis config file not detected! Please run smash ultimate with ARCropolis set up!" I already opened the game, but it keeps sending me that message
> > > Does ARCropolis Ver. 0.9.3 show up on the title screen?
> 
> No ._. , just start normally smash

Did you extract ARCropolis to the right folder?

**Comment by Staichi54** [comment]
> > > > > Follow https://gamebanana.com/tuts/13505
> > > > 
> > > > 
> > > > Say "ARCropolis config file not detected! Please run smash ultimate with ARCropolis set up!" I already opened the game, but it keeps sending me that message
> > > > Does ARCropolis Ver. 0.9.3 show up on the title screen?
> > 
> > 
> > No ._. , just start normally smash
> 
> Did you extract ARCropolis to the right folder?

sd:/atmosphere/contents/01006A800016E000/romfs/skyline/plugins/ 

yes it is on this route, yes

**Comment by Craftyawesome** [comment]
> > > > Follow https://gamebanana.com/tuts/13505
> > > 
> > > 
> > > Say "ARCropolis config file not detected! Please run smash ultimate with ARCropolis set up!" I already opened the game, but it keeps sending me that message
> > > Does ARCropolis Ver. 0.9.3 show up on the title screen?
> 
> No ._. , just start normally smash

What is the full path that ARCropolis is in? Did you copy all of the folders?

**Comment by Staichi54** [comment]
> > > > > Follow https://gamebanana.com/tuts/13505
> > > > 
> > > > 
> > > > Say "ARCropolis config file not detected! Please run smash ultimate with ARCropolis set up!" I already opened the game, but it keeps sending me that message
> > > > Does ARCropolis Ver. 0.9.3 show up on the title screen?
> > 
> > 
> > No ._. , just start normally smash
> 
> What is the full path that ARCropolis is in? Did you copy all of the folders?

yes, i copy all the folders

**Comment by Craftyawesome** [comment]
> > > > > > Follow https://gamebanana.com/tuts/13505
> > > > > 
> > > > > 
> > > > > Say "ARCropolis config file not detected! Please run smash ultimate with ARCropolis set up!" I already opened the game, but it keeps sending me that message
> > > > > Does ARCropolis Ver. 0.9.3 show up on the title screen?
> > > 
> > > 
> > > No ._. , just start normally smash
> > 
> > 
> > What is the full path that ARCropolis is in? Did you copy all of the folders?
> 
> yes, i copy all the folders

Try clearing the 01006A... folder and reinstalling ARCropolis. (You will have to reinstall this mod later)

**Comment by Staichi54** [comment]
> > > > > > > Follow https://gamebanana.com/tuts/13505
> > > > > > 
> > > > > > 
> > > > > > Say "ARCropolis config file not detected! Please run smash ultimate with ARCropolis set up!" I already opened the game, but it keeps sending me that message
> > > > > > Does ARCropolis Ver. 0.9.3 show up on the title screen?
> > > > 
> > > > 
> > > > No ._. , just start normally smash
> > > 
> > > 
> > > What is the full path that ARCropolis is in? Did you copy all of the folders?
> > 
> > 
> > yes, i copy all the folders
> 
> Try clearing the 01006A... folder and reinstalling ARCropolis. (You will have to reinstall this mod later)

So... Do I delete everything that is in the folder, also the ultimate folder and the UMM? or just what is in the 01006A?

**Comment by Craftyawesome** [comment]
> So... Do I delete everything that is in the folder, also the ultimate folder and the UMM? or just what is in the 01006A?
Delete 01006A800016E000 entirely. If it isn't loading at all, the other folders shouldn't be a problem. Then reinstall ARCropolis. It should hopefully generate a config.

**Comment by Staichi54** [comment]
> > So... Do I delete everything that is in the folder, also the ultimate folder and the UMM? or just what is in the 01006A?
> 
> Delete 01006A800016E000 entirely. If it isn't loading at all, the other folders shouldn't be a problem. Then reinstall ARCropolis. It should hopefully generate a config.

Thank you so muchi, i just have a question, How i can open the menu for Change the skin?

**Comment by Craftyawesome** [comment]
> Thank you so muchi, i just have a question, How i can open the menu for Change the skin?

So you got ARCropolis working? Install this mod, and choose steve and maybe hit the skin change button.

**Comment by Staichi54** [comment]
> > Thank you so muchi, i just have a question, How i can open the menu for Change the skin?
> 
> So you got ARCropolis working? Install this mod, and choose steve and maybe hit the skin change button.

Which is the skin change button? (This is the last)

**Comment by Craftyawesome** [comment]
> > > Thank you so muchi, i just have a question, How i can open the menu for Change the skin?
> > 
> > 
> > So you got ARCropolis working? Install this mod, and choose steve and maybe hit the skin change button.
> 
> Which is the skin change button? (This is the last)

The in-game one. L or R.

**Comment by Staichi54** [comment]
> > > > Thank you so muchi, i just have a question, How i can open the menu for Change the skin?
> > > 
> > > 
> > > So you got ARCropolis working? Install this mod, and choose steve and maybe hit the skin change button.
> > 
> > 
> > Which is the skin change button? (This is the last)
> 
> The in-game one. L or R.

Thank you so much <3
