### ISSUE TITLE
Switch Hard locks [MAJOR ISSUE]

### ISSUE THREAD

**Issue by kckarnige** [jam1garner/smash-minecraft-skins#31]
Everytime I select a skin, my switch hard locks, and I have to reboot it

**Comment by Manito418** [comment]
This happens to me too but, it only happened since I installed sys-hidplus. So I just uninstalled this mod while I use that. Sys-hidplus seems to conflict with websites and causes the Switch to lock. Do you have sys-hidplus?

**Comment by kckarnige** [comment]
Nope

**Comment by kckarnige** [comment]
I do have other sys-modules, I'm gonna test to see if that's the problem

**Comment by kckarnige** [comment]
**UPDATE:** sys-modules seem to be the problem
