### ISSUE TITLE
looks weird with eyes

### ISSUE THREAD

**Issue by arceuss** [jam1garner/smash-minecraft-skins#4]
![image](https://user-images.githubusercontent.com/28229451/96176351-76e7be80-0ee9-11eb-8e22-da604837e759.png)
![image](https://user-images.githubusercontent.com/28229451/96176383-823aea00-0ee9-11eb-8319-4391dcd081cf.png)
comparison

**Comment by jam1garner** [comment]
This will be fixed when the 2-layer model is included.

**Comment by jam1garner** [comment]
Fixed in 1.1.0
