### ISSUE TITLE
Skins no longer load in game or on ui even after redownload 

### ISSUE THREAD

**Issue by FISHYLAMAR** [jam1garner/smash-minecraft-skins#44]
I did have one skin working before but as soon as I tried downloading another skin after charging my skin on Minecraft java it started not working not even when I loaded another accounts skin. I've tried to redownload the files to get it to work and even threw the skin files in the directory itself but they still won't load

**Comment by jam1garner** [comment]
You likely updated arcropolis, which currently does not provide an API until some dust has settled on 1.0. Closing this, feel free to reopen after arcropolis has an API again if the issue persists.
