### ISSUE TITLE
Doesn't Work Properly

### ISSUE THREAD

**Issue by Benjamoose** [jam1garner/smash-minecraft-skins#46]
Seems like there needs to be an update for the latest ARCropolis potentially.

The plugin loads with the game, the menu also pops up showing the skins, but it doesn't get applied when you launch the battle, instead just sticking to the stock Steve and Alex skins.

It also seems like it lags for a second before popping up the menu and then again after selecting (closing the menu).

**Comment by jam1garner** [comment]
Arcropolis 1.0 doesn't have an API yet, once it does support will be added.

**Comment by Benjamoose** [comment]
Ah! That's totally understandable. Thanks for the response.

**Comment by jam1garner** [comment]
Fixed in latest version
