### ISSUE TITLE
Doesn't work (And why)

### ISSUE THREAD

**Issue by Texthead** [jam1garner/smash-minecraft-skins#49]
The mod should work fine on any version of Super Smash Bros. Ultimate. I'm sure the problem is that the mod is incompatible with Acropolis 1.0.0+ due to how API file replacement has been modified. Please have this mod compatible with Arcropolis's changes. I understand the hefty amount of work, and frankly how it may be unneeded due to how the users version of Arcropolis can be changed pretty quickly...

**Comment by Texthead** [comment]
I think the newest version of Smash is incompatible with any version that the mod works on. You will just have to be patient :)

**Comment by jam1garner** [comment]
Fixed in latest version
