### ISSUE TITLE
I cant open up the skin menu

### ISSUE THREAD

**Issue by Rey57234** [jam1garner/smash-minecraft-skins#59]
I have installed mods before and when I try to open up the skin menu when I click Steve it doesn't appear. Do u have to press a certain button or what? If you can help please do. Its on the newest version aswell

**Comment by jam1garner** [comment]
This is likely fixed in the latest release: https://github.com/jam1garner/smash-minecraft-skins/releases/tag/v1.2.5

reopen your issue if the issue persists after updating to smash 13.0.1 + smash-minecraft-skins v1.2.5
