### ISSUE TITLE
libminecraft_skins.nro crashing game

### ISSUE THREAD

**Issue by KHOmega** [jam1garner/smash-minecraft-skins#64]
Atmosphere Version: 1.2.4|S
ARC Version: 2.1.0

When loading up Smash Bros. the application closes.

Game does not close when libminecraft_skins.nro is disabled. No other mods are conflicting.

**Comment by ThatNintendoNerd** [comment]
The problem has been identified. The current release will be updated to contain a hotfix sometime soon.

**Comment by jam1garner** [comment]
@KHOmega try with the new build https://github.com/jam1garner/smash-minecraft-skins/releases/tag/v1.2.4, reopen the issue if it doesn't work
