### ISSUE TITLE
Mod keeps crashing everytime game loads

### ISSUE THREAD

**Issue by APrettyNormalAccount** [jam1garner/smash-minecraft-skins#65]
Like said the game keeps crashing when mod is loaded here's a crash report

[01636325881_01006a800016e000.log](https://github.com/jam1garner/smash-minecraft-skins/files/7493320/01636325881_01006a800016e000.log)
d

**Comment by ThatNintendoNerd** [comment]
The problem has been identified. The current release will be updated to contain a hotfix sometime soon.

**Comment by jam1garner** [comment]
@APrettyNormalAccount try the new build https://github.com/jam1garner/smash-minecraft-skins/releases/tag/v1.2.4, reopen the issue if it doesn't work.
