### ISSUE TITLE
brings up menu, no control

### ISSUE THREAD

**Issue by Fudgecake4567** [jam1garner/smash-minecraft-skins#7]
when i select steve it brings up the selection menu, but im unable to select to add a new skin and i get everything freezes except for the music.

**Comment by jam1garner** [comment]
Would be curious if you or anyone else can find more information as far as recreating. I've heard reinstalling atmosphere fixes it, but I have no clue what is going on here.

**Comment by jam1garner** [comment]
Reinstalling atmosphere has consistently fixed this, closing unless more info is found.
