### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by paceygym** [jam1garner/smash-minecraft-skins#80]
Arc: v3.6.2
Skyline: Mar 05 Beta (latest release)
Smash Ultimate: 13.0.1

Upon booting the game, it immediately crashes. I've checked and double checked that everything is installed correctly and it is. Other users on gamebanana are reporting the same issue. I assume there's incompatibility with the newest version of either smash, skyline, or arc. Would be great if this could be resolved.

Note: I tried using both the latest version of skyline and the one in the release, so I assume the issue is with the newest version of arc.

**Comment by SubstituteDoll** [comment]
Can cofirm, having the same issue. Smash crashes upon startup. It is, however, indicated that the latest release is for compatibility with ARCropolis 3.0.0, which is the currently latest version. What could the issue be?

**Comment by jam1garner** [comment]
Could you try downgrading to an old version of acropolis and let me know if that resolves the issue? I haven't updated in almost a year so I am not sure how breakage would be on my end

**Comment by SubstituteDoll** [comment]
Sorry, I mistook the latest version of ARCropolis as 3.0.0, when it is 3.13.1 right now. I will try running the mod alone on 3.0.0 and report back. In the mean time, I would like to confirm: ARCropolis is the only framework needed for this, correct?

**Comment by SubstituteDoll** [comment]
> Could you try downgrading to an old version of acropolis and let me know if that resolves the issue? I haven't updated in almost a year so I am not sure how breakage would be on my end

I replaced SD:\atmosphere\contents\01006A800016E000 and SD:\ultimate\arcropolis directories with contents from the 3.0.0 release. Unfortunately, I believe ARCropolis itself is not loading now - smash loads up very normally, just like a vanilla unmodded copy. Going to the eshop menu just brings up the good ol' eshop, confirming that ARCropolis itself probably isn't working correctly now.

**Comment by paceygym** [comment]
Looks like it was a thing on acropolis' side. Things boot just fine now with the newest versions of skyline and Arc. When I downloaded the mod I just did not replace main.npdm or subsdk9 (i.e. Skyline.) Here are the versions I used:

Arcropolis: [v3.13.1] (https://github.com/Raytwo/ARCropolis/tree/v3.13.1)
Skyline: beta 972cdeff  (https://github.com/skyline-dev/skyline/commit/972cdefcbd5dc01e01c91227f31cee50d1ae95d5)
Ultimate: version 13.0.1
Switch version 16.0.0
Atmosphere 1.5.0 (Pre-release on the github)
Hekate 6.0.2

**Comment by paceygym** [comment]
As a side note, when you open the game it immediately pulls up the Steve skin menu sometimes for no reason (only the first time after adding skins so far). Also, it doesn't seem to work in Battle Arenas for some reason. I didn't notice any oddities aside from these.

**Comment by paceygym** [comment]
Oddity spotted, quickplay menu is weird and sometimes opens up whenever an opponent connects. Seems to happen more when it's the first boot of the game maybe.

**Comment by SubstituteDoll** [comment]
> Looks like it was a thing on acropolis' side. Things boot just fine now with the newest versions of skyline and Arc. When I downloaded the mod I just did not replace main.npdm or subsdk9 (i.e. Skyline.) Here are the versions I used:
> 
> Arcropolis: [v3.13.1] (https://github.com/Raytwo/ARCropolis/tree/v3.13.1) Skyline: beta 972cdeff ([skyline-dev/skyline@972cdef](https://github.com/skyline-dev/skyline/commit/972cdefcbd5dc01e01c91227f31cee50d1ae95d5)) Ultimate: version 13.0.1 Switch version 16.0.0 Atmosphere 1.5.0 (Pre-release on the github) Hekate 6.0.2

I still cannot get it to work on the latest Skyline and ARCropolis. The only difference between your setup and mine is the system firmware and atmosphere versions (15.0.1 and 1.4.1), both of which came out after any of the other ones came out so it is my logic that it should work. Could you write your detailed setup process of the mod please?

**Comment by paceygym** [comment]
> > Looks like it was a thing on acropolis' side. Things boot just fine now with the newest versions of skyline and Arc. When I downloaded the mod I just did not replace main.npdm or subsdk9 (i.e. Skyline.) Here are the versions I used:
> > Arcropolis: [v3.13.1] (https://github.com/Raytwo/ARCropolis/tree/v3.13.1) Skyline: beta 972cdeff ([skyline-dev/skyline@972cdef](https://github.com/skyline-dev/skyline/commit/972cdefcbd5dc01e01c91227f31cee50d1ae95d5)) Ultimate: version 13.0.1 Switch version 16.0.0 Atmosphere 1.5.0 (Pre-release on the github) Hekate 6.0.2
> 
> I still cannot get it to work on the latest Skyline and ARCropolis. The only difference between your setup and mine is the system firmware and atmosphere versions (15.0.1 and 1.4.1), both of which came out after any of the other ones came out so it is my logic that it should work. Could you write your detailed setup process of the mod please?

I just copy and pasted the files from the release page directly onto the root of my sd card, taking care not to overwrite main.npdm and subsdk9, as those are the Skyline files. My switch acted strange on the first boot, then hard crashed the system on the second boot, but when I remembered that I had a previous Steve mod downloaded and removed it, things went much better. I'd just double check that you don't have any steve mods, give it a few tries, and double check that arc and especially skyline are up to date.
