### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by kckarnige** [jam1garner/smash-minecraft-skins#9]
If you can use PNGs to changes Steve's skin...can you use PNGs to change different fighters?
In other words, can you make a version of this that works with all fighters?

Why would this be a good idea?
Because it'd be possible to give fighters more skins or hell maybe one day if it's possible, model swaps

**Comment by jam1garner** [comment]
Closing this as "out of scope". I like the idea and I have intended to explore this in other avenues, however, I don't think that's related-enough to this project to keep the issue open. Thank you for your interest.
